server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: asset-service-route
          order: 1
          uri: lb://asset-service
          predicates:
            - Path=/asset-service/**
          filters:
            - StripPrefix=1
            - ApiAuthFilter
        - id: order-service-route
          order: 2
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - ApiAuthFilter
      whitelistUrls: >
        /asset-service/info/version,
        /order-service/info/version